apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kharon
  namespace: kharon
spec:
  interval: 5m
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./deploy/charts/kharon
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: 359546647832.dkr.ecr.us-east-1.amazonaws.com/kharon-dev
      tag: latest # {"$imagepolicy": "flux-system:kharon:tag"}
    replicaCount: 1
    ingress:
      enabled: true
      className: alb
      annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        external-dns.alpha.kubernetes.io/hostname: kharon.dev.mycroftai.org
      hosts:
        - host: kharon.dev.mycroftai.org
          paths:
            - path: /
              pathType: Prefix
